//require("dotenv").config();
import { configDotenv } from "dotenv";
import express from "express";
import crypto from "crypto";
import fs from "fs";
import { createAppAuth } from "@octokit/auth-app";
import { Octokit } from "@octokit/rest";

configDotenv();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(
  express.json({
    verify: (req, res, buf) => {
      req.rawBody = buf;
    },
  })
);

// Verify GitHub webhook signature
function verifySignature(req) {
  const signature = req.headers["x-hub-signature-256"];
  const hmac = crypto.createHmac("sha256", process.env.WEBHOOK_SECRET);
  const digest = "sha256=" + hmac.update(req.rawBody).digest("hex");

  return crypto.timingSafeEqual(
    Buffer.from(signature),
    Buffer.from(digest)
  );
}

async function getInstallationOctokit(installationId) {
  //const privateKey = fs.readFileSync("./private-key.pem", "utf8");
  const privateKey = process.env.GITHUB_PRIVATE_KEY;

  const auth = createAppAuth({
    appId: process.env.APP_ID,
    privateKey,
    installationId,
  });

  const installationAuthentication = await auth({ type: "installation" });

  const octokit = new Octokit({
    auth: installationAuthentication.token,
  });

  return octokit;
}

app.get("/", (req, res) => {
  res.send("AutoSecure GitHub App is running!");
});

app.post("/webhook", async (req, res) => {

  if (!verifySignature(req)) {
    return res.status(401).send("Invalid signature");
  }

  const event = req.headers["x-github-event"];
  console.log("Received Event:", event);

  // Handle installation event
  if (event === "installation") {
    console.log("App installed successfully.");
  }

  // Handle dependabot alert
  if (event === "dependabot_alert") {
    const installationId = req.body.installation.id;
    const repoFullName = req.body.repository.full_name;
    const alertNumber = req.body.alert.number;

    const [owner, repo] = repoFullName.split("/");

    const octokit = await getInstallationOctokit(installationId);
    
    const { data: alert } = 
      await octokit.rest.dependabot.getAlert({
        owner,
        repo,
        alert_number: alertNumber,
      });

    console.log("****** ALERT DETAILS ******");
    console.log("Package:", alert.dependency.package.name);
    console.log("Severity:", alert.security_advisory.severity);
    console.log("Summary:", alert.security_advisory.summary);
    console.log(
      "Patched Version:",
      alert.security_vulnerability.first_patched_version.identifier
    );
    // Fetch default branch information
    const { data: repoData } = await octokit.rest.repos.get({
      owner, 
      repo,
    });

    const defaultBranch = repoData.default_branch;
    console.log("Default Branch:", defaultBranch);

    // Get Latest commit SHA of the default branch
    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });

    const baseeSha = refData.object.sha;
    console.log("Base SHA:", baseeSha);

    // Create a new branch for the fix
    const branchName = `auto-fix-${alert.dependency.package.name}-${Date.now()}`;
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseeSha,
    });

    console.log("Created branch:", branchName);

    // Fetch package.json 
    const { data: fileData } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path: "auto-secure-github/package.json",
      ref: defaultBranch,
    });

    // decode content 
    const content = Buffer.from(fileData.content, "base64").toString();
    const packageJson = JSON.parse(content);


    // update dependency version
    const packageName = alert.dependency.package.name;
    const patchedVersion =
      alert.security_vulnerability.first_patched_version.identifier;

    if (packageJson.dependencies && packageJson.dependencies[packageName]) {
      packageJson.dependencies[packageName] = `^${patchedVersion}`;
    }

    if (packageJson.devDependencies && packageJson.devDependencies[packageName]) {
      packageJson.devDependencies[packageName] = `^${patchedVersion}`;
    }

    // commit changes
    const updatedContent = Buffer.from(
      JSON.stringify(packageJson, null, 2)
    ).toString("base64");

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: "auto-secure-github/package.json",
      message: `fix: auto-upgrade ${packageName} to ${patchedVersion}`,
      content: updatedContent,
      branch: branchName,
      sha:fileData.sha,
    });

    // create pull request
    await octokit.rest.pulls.create({
      owner,
      repo,
      title: `🔒 Auto Security Fix: Upgrade ${packageName} to ${patchedVersion}`,
      head: branchName,
      base: defaultBranch,
      body: `
    This PR was automatically generated by AutoSecure AI Agent.

    ### Vulnerability Details
    - Package: ${packageName}
    - Severity: ${alert.security_advisory.severity}
    - Summary: ${alert.security_advisory.summary}

    ### Fix Applied
    Upgraded to version ${patchedVersion} which contains the security patch.
    `,
    });

    console.log("Pull request created successfully.");

  }
  


  res.status(200).send("Event processed");
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// Version: 1.0.0
